version: '3.5'
services:
  igparser:
    privileged: false
    build: .
    restart: always
    volumes:
      - "./logs:/logs"
    environment:
      IG_PARSER_PORT: "8080"
      IG_PARSER_LOGGING: "true"
      IG_PARSER_LOGGING_PATH: "/logs"
    ports:
      - '4040:8080'
    network_mode: "host"