version: '3.5'
services:
  go_vue_template:
    privileged: false
    build: .
    restart: always
    volumes:
      - "./logs:/logs"
    environment:
      GO_VUE_TEMPLATE_PORT: "8080"
      GO_VUE_TEMPLAT_LOGGING: "true"
      GO_VUE_TEMPLATE_LOGGING_PATH: "/logs"
    ports:
      - '4040:8080'
    network_mode: "host"
